version: "3"

services:
  web:
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUNBUFFERED: 1
      HASHID_SALT: "123456"
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - "db"
    volumes:
      - "./src:/app"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
volumes:
  dev_volume:
    driver: local
